### ISSUE TITLE
Tests fail when environment sets -Copt-level > 0

### ISSUE THREAD

**Issue by kentfredric** [mbrubeck/rust-debug-unreachable#1]
My understanding is that this is somewhat intended behaviour, and my imagination is a bit limited as to how you might handle this so it does the right thing regardless of the -Copt-level settings.

Ideally, tests should pass when built with optimizations, and I have a suspicion this also lends itself to interesting problems if consuming crates also have tests for this path `panic()`'ing.

For now, I've put in place a workaround for this crate in our vendor toolchain to override our normal value ( `-Copt-level=3 -Cdebuginfo=2` ) with `RUSTFLAGS="${RUSTFLAGS} -Copt-level=0"`, but it would be better overall if this wasn't necessary.

### Reproduction

```
 RUSTFLAGS="-Copt-level=1" cargo test
```
```
   Compiling new_debug_unreachable v1.0.3 (<prefix>/new_debug_unreachable-1.0.3)
    Finished test [unoptimized + debuginfo] target(s) in 14.24s
     Running target/debug/deps/debug_unreachable-faa1ef4627bb2a7a

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/check-74a7bcf49a536e5d

running 1 test
error: test failed, to rerun pass '--test check'

Caused by:
  process didn't exit successfully: `<prefix>/new_debug_unreachable-1.0.3/target/debug/deps/check-74a7bcf49a536e5d` (signal: 4, SIGILL: illegal instruction)
```
### Stack Traces
<details>
<summary>GDB</summary>

```
Thread 2 "explodes_in_deb" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff7c17700 (LWP 16217)]
0x0000555555563250 in core::ops::function::FnOnce::call_once ()
(gdb) bt
#0  0x0000555555563250 in core::ops::function::FnOnce::call_once ()
#1  0x000055555556f07f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
#2  0x00005555555b821a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:78
#3  0x000055555558a337 in std::panicking::try ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270
#4  std::panic::catch_unwind () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
#5  test::run_test_in_process () at src/libtest/lib.rs:567
#6  test::run_test::run_test_inner::{{closure}} () at src/libtest/lib.rs:474
#7  0x0000555555563826 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/sys_common/backtrace.rs:136
#8  0x0000555555567ba6 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:469
#9  <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318
#10 std::panicking::try::do_call () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292
#11 0x00005555555b821a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:78
#12 0x0000555555568626 in std::panicking::try ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270
#13 std::panic::catch_unwind () at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
#14 std::thread::Builder::spawn_unchecked::{{closure}} ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:468
#15 core::ops::function::FnOnce::call_once{{vtable-shim}} ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
#16 0x00005555555a5e1f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
#17 0x00005555555b76f0 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
#18 std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:13
#19 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:80
#20 0x00007ffff7f512d7 in start_thread (arg=<optimized out>) at pthread_create.c:479
#21 0x00007ffff7e656df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
</details>
<details>
<summary>lldb</summary>

```
Process 16262 stopped
* thread #2, name = 'explodes_in_deb', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x0000555555563250 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once::h41c6efecde8bd3e6
check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once::h41c6efecde8bd3e6:
->  0x555555563250 <+0>: ud2    
    0x555555563252:      nopw   %cs:(%rax,%rax)
    0x55555556325c:      nopl   (%rax)
check-74a7bcf49a536e5d`check::main::hf93736f22994602c:
    0x555555563260 <+0>: leaq   0x92291(%rip), %rdi
(lldb) bt   
* thread #2, name = 'explodes_in_deb', stop reason = signal SIGILL: illegal instruction operand
  * frame #0: 0x0000555555563250 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once::h41c6efecde8bd3e6
    frame #1: 0x000055555556f07f check-74a7bcf49a536e5d`_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hac6c943802a69b63 at boxed.rs:1022:8
    frame #2: 0x00005555555b821a check-74a7bcf49a536e5d`__rust_maybe_catch_panic at lib.rs:78:7
    frame #3: 0x000055555558a337 check-74a7bcf49a536e5d`test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h124724482e4d2ce7 [inlined] std::panicking::try::he87184946bc6dd10 at panicking.rs:270:12
    frame #4: 0x000055555558a2ea check-74a7bcf49a536e5d`test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h124724482e4d2ce7 [inlined] std::panic::catch_unwind::hf7ba6a4b1c41a214 at panic.rs:394
    frame #5: 0x000055555558a2ea check-74a7bcf49a536e5d`test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h124724482e4d2ce7 [inlined] test::run_test_in_process::h2b9b8139b389f254 at lib.rs:567
    frame #6: 0x000055555558a2cf check-74a7bcf49a536e5d`test::run_test::run_test_inner::_$u7b$$u7b$closure$u7d$$u7d$::h124724482e4d2ce7 at lib.rs:474
    frame #7: 0x0000555555563826 check-74a7bcf49a536e5d`std::sys_common::backtrace::__rust_begin_short_backtrace::h7bbe1dcc3508cbda at backtrace.rs:136:4
    frame #8: 0x0000555555567ba6 check-74a7bcf49a536e5d`std::panicking::try::do_call::h323fa928e0264a15 [inlined] std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf74b48dbc6ccd6dc at mod.rs:469:16
    frame #9: 0x0000555555567b90 check-74a7bcf49a536e5d`std::panicking::try::do_call::h323fa928e0264a15 [inlined] _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h3bf7ff98f40bd74d at panic.rs:318
    frame #10: 0x0000555555567b90 check-74a7bcf49a536e5d`std::panicking::try::do_call::h323fa928e0264a15 at panicking.rs:292
    frame #11: 0x00005555555b821a check-74a7bcf49a536e5d`__rust_maybe_catch_panic at lib.rs:78:7
    frame #12: 0x0000555555568626 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h40fa05e88c801467 [inlined] std::panicking::try::hd118dcf5026fdb8f at panicking.rs:270:12
    frame #13: 0x00005555555685e7 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h40fa05e88c801467 [inlined] std::panic::catch_unwind::h9234fc4bb54734e4 at panic.rs:394
    frame #14: 0x00005555555685e7 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h40fa05e88c801467 [inlined] std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::hdb131e70b78bce7b at mod.rs:468
    frame #15: 0x00005555555685b3 check-74a7bcf49a536e5d`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h40fa05e88c801467 at function.rs:232
    frame #16: 0x00005555555a5e1f check-74a7bcf49a536e5d`_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hbabfae4f70ab9609 at boxed.rs:1022:8
    frame #17: 0x00005555555b76f0 check-74a7bcf49a536e5d`std::sys::unix::thread::Thread::new::thread_start::h3f42d1616b825de5 [inlined] _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h8471b989095c2da7 at boxed.rs:1022:8
    frame #18: 0x00005555555b76e4 check-74a7bcf49a536e5d`std::sys::unix::thread::Thread::new::thread_start::h3f42d1616b825de5 [inlined] std::sys_common::thread::start_thread::h0647e91c8800cb8c at thread.rs:13
    frame #19: 0x00005555555b766a check-74a7bcf49a536e5d`std::sys::unix::thread::Thread::new::thread_start::h3f42d1616b825de5 at thread.rs:80
    frame #20: 0x00007ffff7f512d7 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:479:8
    frame #21: 0x00007ffff7e656df libc.so.6`__GI___clone at clone.S:95
```
</details>

### Binary
[check-74a7bcf49a536e5d.gz](https://github.com/mbrubeck/rust-debug-unreachable/files/4010970/check-74a7bcf49a536e5d.gz)

**Comment by mbrubeck** [comment]
Fixed by disabling this test in optimized builds.
